### PR TITLE
Add Godeps

### PR DESCRIPTION
**Pull request by simonjohansson**
Title says it all :)

### CODE REVIEW

**Comment by dsabeti** [comment]
Is the intent behind the PR to be able to deploy the nozzle as a CF app? The datadog-firehose-nozzle was originally intended to be a bosh deployment, so we develop the datadog-firehose-nozzle by setting our GOPATH to be [this folder](https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle-release/tree/master/src/datadog-firehose-nozzle) in the datadog-firehose-nozzle-release repository.

**Comment by simonjohansson** [comment]
@dsabeti 

Mainly to be able to deploy in CF yes.

**Comment by roxtar** [comment]
We will be waiting on this PR till we decide if we want to support the nozzle as a CF deployable app. Refer https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle/issues/2

**Comment by erikjasiak** [comment]
Closing  :-/  please see reasoning in the [related issue filed here.](https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle/issues/2)

Erik

**Pull request closed without merging**
